apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-backend
  labels:
    app.kubernetes.io/name: ingest-backend
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingest-backend
      app.kubernetes.io/instance: ingest-backend
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingest-backend
        app.kubernetes.io/instance: ingest-backend
        app.kubernetes.io/component: service
        app.kubernetes.io/created-by: cli
    spec:
      serviceAccountName: ingest-backend-sa
      containers:
        - name: ingest-backend
          image: 585990787062.dkr.ecr.us-east-1.amazonaws.com/ner-using-spacy-backend:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ingest-backend-config
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 256Mi
            requests:
              cpu: 1000m
              memory: 128Mi