apiVersion: v1
kind: Service
metadata:
  name: ingest-backend
  labels:
    app.kubernetes.io/created-by: cli
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ingest-backend
    app.kubernetes.io/instance: ingest-backend
    app.kubernetes.io/component: service